controllers:
    resource: ../../src/Controller/*
    exclude: ../../src/Controller/Api
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api/*
    name_prefix: api_
    prefix: api/
    type: annotation
